url: ""
name: "Apache AsterixDB"

STABLE_VERSION: 0.9.1
UNSTABLE_VERSION: 0.9.2-SNAPSHOT
STABLE_DOWNLOAD_URL: "http://www.apache.org/dyn/closer.lua/asterixdb/asterixdb-0.9.1/asterix-installer-0.9.1-binary-assembly.zip"
UNSTABLE_DOWNLOAD_URL: "https://asterix-jenkins.ics.uci.edu/job/asterix-integration-tests/lastSuccessfulBuild/org.apache.asterix$asterix-installer/artifact/org.apache.asterix/asterix-installer/0.9.2-SNAPSHOT/asterix-installer-0.9.2-SNAPSHOT-binary-assembly.zip"
STABLE_YARN_URL: "http://www.apache.org/dyn/closer.lua/asterixdb/asterixdb-0.9.1/asterix-yarn-0.9.1-binary-assembly.zip"
UNSTABLE_YARN_URL: "https://asterix-jenkins.ics.uci.edu/job/asterix-integration-tests/lastSuccessfulBuild/org.apache.asterix$asterix-yarn/artifact/org.apache.asterix/asterix-yarn/0.9.2-SNAPSHOT/asterix-yarn-0.9.2-SNAPSHOT-binary-assembly.zip"
STABLE_NCSERVICE_URL: "http://www.apache.org/dyn/closer.lua/asterixdb/asterixdb-0.9.1/asterix-server-0.9.1-binary-assembly.zip"
UNSTABLE_NCSERVICE_URL: "https://asterix-jenkins.ics.uci.edu/job/asterix-integration-tests/lastSuccessfulBuild/org.apache.asterix$asterix-server/artifact/org.apache.asterix/asterix-server/0.9.2-SNAPSHOT/asterix-server-0.9.2-SNAPSHOT-binary-assembly.zip"
DOCS_BASE_URL: "docs"
UNSTABLE_DOCS_BASE_URL: "https://ci.apache.org/projects/asterixdb/"
ICS_DOWNLOAD_BASE_URL: "https://asterixdb.ics.uci.edu/download"

# Build settings
destination: content
defaults:
  -
    scope:
      path: ""
    values:
      layout: plain

markdown: kramdown
highlighter: pygments

kramdown:
    toc_levels: 1..3
    input: GFM
    hard_wrap: false

redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink",
               "tables", "with_toc_data", "strikethrough", "superscript",
               "lax_spacing"]

